# ========================================================================
#  PLOT_DEFAULTS.jl — Global plot configuration and helpers
# ========================================================================
#
# Description:
#   Provides consistent, publication-quality plot defaults for all figures
#   generated by the solver.  Call SET_PLOT_DEFAULTS() once before any
#   plotting to apply global PyPlot/matplotlib settings (font sizes,
#   frame style, background).
#
#   Also provides:
#     auto_figure_size      — compute (width, height) from data aspect ratio
#     curvilinear_heatmap   — smooth pseudocolor plot using PyPlot pcolormesh
#                             for correct rendering on curvilinear grids
#     save_or_display_figure — display a figure interactively when a display
#                              server is available, or save to PNG on headless
#                              Linux systems.
#
# Usage:
#   SET_PLOT_DEFAULTS(output_dir=joinpath(@__DIR__,"output"))  # call once in main.jl
#   sz = auto_figure_size(x, y)                          # data-adaptive figure size
#   fig, ax = curvilinear_heatmap(x, y, z)               # smooth filled plot
#   save_or_display_figure(fig)                           # works on headless Linux
#
# Part of: Hypersonics Stability Solver — Postprocessing Module


# Global flag: true when no display server is detected (headless Linux).
const _HEADLESS = Ref(false)
# Counter for auto-naming saved figures when no explicit name is given.
const _FIG_COUNTER = Ref(0)
# Output directory for saved figures.
const _FIG_OUTPUT_DIR = Ref("figures")
# Whether the output directory has been explicitly set by the user.
const _OUTPUT_DIR_SET = Ref(false)


"""
    _detect_headless() -> Bool

Return `true` when running on Linux without a display server (DISPLAY and
WAYLAND_DISPLAY are both unset or empty).
"""
function _detect_headless()
    Sys.islinux() || return false
    disp = get(ENV, "DISPLAY", "")
    wayl = get(ENV, "WAYLAND_DISPLAY", "")
    return isempty(disp) && isempty(wayl)
end


"""
    SET_PLOT_DEFAULTS(; output_dir=nothing)

Apply global PyPlot (matplotlib) defaults so that every subsequent plot
inherits consistent font sizes, margins, frame style, and background.

Call once with an explicit `output_dir` at the top of your main script
(e.g. `SET_PLOT_DEFAULTS(output_dir=joinpath(@__DIR__, "output"))`).
Internal helper functions may call `SET_PLOT_DEFAULTS()` (no arguments)
to ensure rc params are applied; in that case the previously configured
output directory is preserved.

Figures are always rendered with the non-interactive "Agg" backend and
saved to `output_dir` (created automatically if it does not exist).
"""
function SET_PLOT_DEFAULTS(; output_dir::Union{String,Nothing}=nothing)
    # Detect headless environment
    _HEADLESS[] = _detect_headless()
    # Always use non-interactive backend (Agg) so figures are saved to disk.
    # This avoids issues in VS Code terminals and headless servers alike.
    PyPlot.matplotlib.use("Agg")

    # Only update the output directory when explicitly provided, so that
    # internal callers (PLOT_RUNNING, PLOT_MODES, …) do not overwrite
    # the path configured by the user's main script.
    if output_dir !== nothing
        _FIG_OUTPUT_DIR[] = output_dir
        _OUTPUT_DIR_SET[] = true
        mkpath(output_dir)
        @info "Figures will be saved to \"$output_dir/\""
    elseif !_OUTPUT_DIR_SET[]
        # First call ever and no explicit dir → fall back to "figures"
        mkpath(_FIG_OUTPUT_DIR[])
    end

    PyPlot.rc("font",   size=12)
    PyPlot.rc("axes",   titlesize=14, labelsize=14, facecolor="white",
              grid=false, linewidth=1.0)
    PyPlot.rc("xtick",  labelsize=12)
    PyPlot.rc("ytick",  labelsize=12)
    PyPlot.rc("legend", fontsize=12)
    PyPlot.rc("figure", facecolor="white", dpi=150)
    PyPlot.rc("savefig", dpi=150)
end


"""
    save_or_display_figure(fig; name="")

Save `fig` as a PNG file and close it to free memory.  The file is written
to the output directory configured by `SET_PLOT_DEFAULTS` (default: "figures/"
relative to the working directory, or the explicit path passed in `main.jl`).

Keyword arguments:
    name — base filename (without extension).  When empty, an auto-
           incrementing counter is used (e.g. "figure_001.png").
"""
function save_or_display_figure(fig; name::String="")
    if isempty(name)
        _FIG_COUNTER[] += 1
        name = @sprintf("figure_%03d", _FIG_COUNTER[])
    end
    # Ensure the output directory exists (no-op if it already does)
    mkpath(_FIG_OUTPUT_DIR[])
    fpath = joinpath(_FIG_OUTPUT_DIR[], name * "_out.png")
    fig.savefig(fpath, bbox_inches="tight")
    @info "Figure saved to $fpath"
    PyPlot.close(fig)          # free memory — prevents "too many open figures" warning
end


"""
    auto_figure_size(x, y; max_width=900, max_height=800,
                     margin_x=150, margin_y=120) -> (Int, Int)

Compute figure dimensions (in pixels) that preserve the data aspect ratio
while fitting within a maximum bounding box.  `margin_x` / `margin_y`
account for axes labels, tick labels, and colorbar space.

Inputs:
    x, y      — coordinate arrays (any AbstractArray); only extremes used.
    max_width  — maximum figure width  [px].
    max_height — maximum figure height [px].
    margin_x   — horizontal pixel budget for labels + colorbar.
    margin_y   — vertical   pixel budget for title + labels.

Returns:
    (width, height) tuple in pixels, suitable for `size=(w, h)`.
"""
function auto_figure_size(x, y; max_width=900, max_height=800,
                          margin_x=150, margin_y=120)
    width_range  = maximum(x) - minimum(x)
    height_range = maximum(y) - minimum(y)

    if width_range == 0 || height_range == 0
        return (max_width, max_height)
    end

    data_aspect = height_range / width_range

    avail_w = max_width  - margin_x
    avail_h = max_height - margin_y

    if data_aspect > avail_h / avail_w
        # height-constrained
        plot_h = avail_h
        plot_w = round(Int, plot_h / data_aspect)
    else
        # width-constrained
        plot_w = avail_w
        plot_h = round(Int, plot_w * data_aspect)
    end

    fig_w = plot_w + margin_x
    fig_h = plot_h + margin_y

    return (max(fig_w, 500), max(fig_h, 400))
end


"""
    curvilinear_heatmap(x, y, z; kwargs...) -> (fig, ax)

Create a smooth pseudocolor plot using PyPlot's `pcolormesh` with Gouraud
shading, suitable for curvilinear grids where x, y are full 2-D coordinate
arrays (not 1-D vectors).

Inputs:
    x, y    — (2-D arrays) physical coordinates at each grid point.
    z       — (2-D array) scalar field to plot (same size as x, y).

Keyword arguments:
    clims           — (lo, hi) tuple for colour limits, or :auto / nothing.
    cmap            — colormap name (Symbol or String). Default: :turbo
                      (falls back to :jet if turbo is unavailable).
    colorbar_label  — label string for the colorbar.
    xlabel_str      — x-axis label.
    ylabel_str      — y-axis label.
    title_str       — subplot title.
    fig_size        — (width, height) in pixels; converted to inches at 100 dpi.
    ax              — existing PyPlot axis to plot into (for subplots).
                      When nothing, a new figure is created.

Returns:
    (fig, ax) — PyPlot figure and axis handles for further overlay.
"""
function curvilinear_heatmap(x_coords::AbstractMatrix, y_coords::AbstractMatrix,
                             c_data::AbstractMatrix;
                             clims=nothing, cmap=nothing,
                             colorbar_label="", xlabel_str="", ylabel_str="",
                             title_str="", fig_size=nothing, ax=nothing)

    # Determine colormap: prefer turbo, fall back to jet
    if cmap === nothing || cmap === :turbo || cmap == "turbo"
        cmap_name = try
            PyPlot.matplotlib.cm.get_cmap("turbo")
            "turbo"
        catch
            "jet"
        end
    else
        cmap_name = string(cmap)
    end

    # Create or reuse axes
    if ax === nothing
        fig, ax = PyPlot.subplots()
        if fig_size !== nothing
            fig.set_size_inches(fig_size[1] / 100.0, fig_size[2] / 100.0)
        end
    else
        fig = ax.get_figure()
    end

    # Plot with pcolormesh + Gouraud shading for smooth interpolation
    if clims !== nothing && clims !== :auto && clims isa Tuple
        pcm = ax.pcolormesh(x_coords, y_coords, c_data,
                            cmap=cmap_name, shading="gouraud",
                            vmin=clims[1], vmax=clims[2])
    else
        pcm = ax.pcolormesh(x_coords, y_coords, c_data,
                            cmap=cmap_name, shading="gouraud")
    end

    PyPlot.colorbar(pcm, ax=ax, label=colorbar_label)
    ax.set_aspect("equal")

    if !isempty(xlabel_str)
        ax.set_xlabel(xlabel_str)
    end
    if !isempty(ylabel_str)
        ax.set_ylabel(ylabel_str)
    end
    if !isempty(title_str)
        ax.set_title(title_str)
    end

    return (fig, ax)
end
